name: moontime
description: A new Flutter project.

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7
  flutter_secure_storage: ^6.1.0
  tuple: ^2.0.1
  get: ^4.6.5
  get_storage: ^2.0.3
  easy_debounce: ^2.0.2+1
  url_launcher: ^6.1.7
  permission_handler: ^10.2.0
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  flutter_slidable: ^2.0.0
  jiffy: ^5.0.0
  like_button: ^2.0.5
  shimmer: ^2.0.0
  custom_pop_up_menu: ^1.2.4
  readmore: ^2.2.0
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter_animate: ^2.0.1
  iconly: ^1.0.1
  flutter_native_splash: ^2.2.16
  blurrycontainer: ^1.0.2
  carousel_slider: ^4.2.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  flutter_html: ^2.2.1

dependency_overrides:
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Isidora
      fonts:
        - asset: assets/fonts/isidora-medium.otf
          weight: 100
        - asset: assets/fonts/isidora-semibold.otf
          weight: 200
        - asset: assets/fonts/isidora-semibold.otf
          weight: 300
        - asset: assets/fonts/isidora-bold.otf
          weight: 400
        - asset: assets/fonts/isidora-bold.otf
          weight: 500
        - asset: assets/fonts/isidora-black.otf
          weight: 600
        - asset: assets/fonts/isidora-black.otf
          weight: 700
    - family: IsidoraSans
      fonts:
        - asset: assets/fonts/IsidoraSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IsidoraSans-Light.otf
          weight: 200
        - asset: assets/fonts/IsidoraSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/IsidoraSans-Medium.otf
          weight: 400
        - asset: assets/fonts/IsidoraSans-SemiBold.otf
          weight: 500
        - asset: assets/fonts/IsidoraSans-Bold.otf
          weight: 600
        - asset: assets/fonts/IsidoraSans-Black.otf
          weight: 700

  assets:
    - assets/images/
    - assets/icons/

