name: moontime
description: A new Flutter project.

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7
  flutter_secure_storage: ^6.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^1.1.6
  easy_debounce: ^2.0.2+1
  url_launcher: ^6.1.7
  permission_handler: ^10.2.0
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  flutter_slidable: ^2.0.0
  jiffy: ^5.0.0
  like_button: ^2.0.5
  shimmer: ^2.0.0
  custom_pop_up_menu: ^1.2.4
  readmore: ^2.2.0
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

