// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNnQcxKisqxuinl-C4FDbogQDUS9vqZk',
    appId: '1:35940773750:android:b9f1cdd8c865fd4be7d457',
    messagingSenderId: '35940773750',
    projectId: 'moontime-io',
    storageBucket: 'moontime-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLEXflndaU2z_c2d8oZDiPf8IulF5lhg',
    appId: '1:35940773750:ios:bd771dce3a962804e7d457',
    messagingSenderId: '35940773750',
    projectId: 'moontime-io',
    storageBucket: 'moontime-io.appspot.com',
    androidClientId: '35940773750-09dpmfjdot9n6cajbrgddlprpe25qr53.apps.googleusercontent.com',
    iosClientId: '35940773750-7q2cutjfp0dko1rk3i8fikm2urd77h20.apps.googleusercontent.com',
    iosBundleId: 'co.desense.moontime',
  );
}
